// The sequence of triangle numbers if generated by
// adding the natural numbers. So the 7th triangle
// number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
// The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
// 28 is the first triangle number to have 6 divisors.
// What is the value of the first triangle number to 
// have over five hundred divisors?

public class Problem012 {
	public static void main(String[] args) {
		Kirill.main();
	}
}

class Kirill {
	static void main() {
		long num = 0;
		int maxDivisors = 1;
		for (int i=1;i<10_000;i++) {
			num += i;
			if (numOfDivisors(num) > maxDivisors) {
				maxDivisors = numOfDivisors(num);
				System.out.println(i + "th triangle number: " + num);
				System.out.println("Divisors: " + maxDivisors);
			}
		}
	}

	static int numOfDivisors(long num) {
		int numOfDivisors = 1;
		for (long i=2;i<=num;i++)
			if (num % i == 0)
				numOfDivisors++; 
		return numOfDivisors;
	}
}
